POST http://localhost:4500/signup
Content-Type: application/json


{
    "firstName": "Anushka",
    "lastName": "Singfh",
    "email": "chobdfbjk@gmail.com",
    "password": "Sidharth",
    "mobileNumber": "8448605993"
    
}

###

POST http://localhost:4500/login
Content-Type: application/json

{
    "email": "chobdfbjk@gmail.com",
    "password": "Sidharth"
}